/*
Sales Performance Analytics Dashboard
Well-commented SQL analysis queries for KPI reporting and business insights.

Database: data/sales_performance.db
Table: sales_orders

How to use:
1. Run python scripts/run_pipeline.py to create the database.
2. Open data/sales_performance.db in a SQLite tool.
3. Run the queries below one at a time.
*/

-- 1. Total sales
-- Business question: What is the total sales revenue generated by all orders?
SELECT
    ROUND(SUM(sales), 2) AS total_sales
FROM sales_orders;

-- 2. Total profit
-- Business question: How much total profit did the business generate?
SELECT
    ROUND(SUM(profit), 2) AS total_profit
FROM sales_orders;

-- 3. Total number of orders
-- Business question: How many unique customer orders were placed?
SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM sales_orders;

-- 4. Average order value
-- Business question: How much sales revenue does the average order generate?
SELECT
    ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM sales_orders;

-- 5. Monthly sales trend
-- Business question: How does sales performance change month over month?
SELECT
    order_month,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM sales_orders
GROUP BY order_month
ORDER BY order_month;

-- 6. Sales by region
-- Business question: Which regions generate the most sales?
SELECT
    region,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(profit) / NULLIF(SUM(sales), 0), 4) AS profit_margin
FROM sales_orders
GROUP BY region
ORDER BY total_sales DESC;

-- 7. Profit by product category
-- Business question: Which product categories are most profitable?
SELECT
    product_category,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    SUM(quantity) AS total_quantity,
    ROUND(SUM(profit) / NULLIF(SUM(sales), 0), 4) AS profit_margin
FROM sales_orders
GROUP BY product_category
ORDER BY total_profit DESC;

-- 8. Top 10 products by sales
-- Business question: Which products are the largest revenue drivers?
SELECT
    product_name,
    product_category,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    SUM(quantity) AS total_quantity,
    ROUND(SUM(profit) / NULLIF(SUM(sales), 0), 4) AS profit_margin
FROM sales_orders
GROUP BY product_name, product_category
ORDER BY total_sales DESC
LIMIT 10;

-- 9. Customer segment performance
-- Business question: Which customer segments generate the most sales and profit?
SELECT
    customer_segment,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS average_order_value,
    ROUND(SUM(profit) / NULLIF(SUM(sales), 0), 4) AS profit_margin
FROM sales_orders
GROUP BY customer_segment
ORDER BY total_sales DESC;

-- 10. Discount impact on profit
-- Business question: Are discounts helping sales while reducing profitability?
SELECT
    CASE
        WHEN discount = 0 THEN 'No Discount'
        WHEN discount <= 0.10 THEN 'Low Discount'
        WHEN discount <= 0.20 THEN 'Medium Discount'
        ELSE 'High Discount'
    END AS discount_band,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(AVG(discount), 3) AS average_discount,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND(SUM(profit) / NULLIF(SUM(sales), 0), 4) AS profit_margin
FROM sales_orders
GROUP BY discount_band
ORDER BY average_discount;

-- 11. Low-profit or high-discount products
-- Business question: Which products may need pricing, discount, or margin review?
SELECT
    product_name,
    product_category,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND(AVG(discount), 3) AS average_discount,
    ROUND(SUM(profit) / NULLIF(SUM(sales), 0), 4) AS profit_margin,
    COUNT(DISTINCT order_id) AS total_orders
FROM sales_orders
GROUP BY product_name, product_category
HAVING profit_margin < 0.10
    OR average_discount >= 0.15
ORDER BY profit_margin ASC, average_discount DESC;

-- 12. State-level sales and profit
-- Business question: Which states are strongest within each region?
SELECT
    state,
    region,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(profit) / NULLIF(SUM(sales), 0), 4) AS profit_margin
FROM sales_orders
GROUP BY state, region
ORDER BY total_sales DESC;
